#!/usr/bin/env bash
#
# Issue a certificate for a verified customer domain and give it its own nginx
# server block.
#
# Called by the app when a domain verifies (see src/lib/certs.ts), and safe to
# run by hand for a domain that was verified before this existed.
#
#   ./issue-cert.sh portfolio.someone.com
#
# This is the nginx equivalent of Caddy's on-demand TLS. It is deliberately a
# script rather than app code: issuing a certificate touches the whole box's
# web server, and a thing that reloads nginx should be readable in one screen
# by whoever is holding the pager.
#
# Install: the app calls it at the path in CERT_ISSUE_COMMAND. Unset that and
# nothing here ever runs.
set -euo pipefail

HOST="${1:-}"
WEBROOT="${CERT_WEBROOT:-/var/www/certbot}"
UPSTREAM="${CERT_UPSTREAM:-127.0.0.1:3004}"
SITES="${CERT_NGINX_DIR:-/etc/nginx/sites-available}"
ENABLED="${CERT_NGINX_ENABLED_DIR:-/etc/nginx/sites-enabled}"

# Validated again here, not just in the app. This string reaches certbot and a
# filename, and "the caller checked it" is how that goes wrong one refactor
# from now.
if ! [[ "$HOST" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]]; then
  echo "issue-cert: refusing hostname: ${HOST}" >&2
  exit 2
fi

# One at a time. Two certbot runs at once fight over the same account lock, and
# two nginx reloads at once can race a half-written block.
exec 9>"/var/lock/issue-cert.lock"
if ! flock -n 9; then
  echo "issue-cert: another run holds the lock; skipping ${HOST}" >&2
  exit 3
fi

if [[ -d "/etc/letsencrypt/live/${HOST}" ]]; then
  echo "issue-cert: certificate for ${HOST} already exists"
else
  mkdir -p "${WEBROOT}/.well-known/acme-challenge"
  # webroot, not the nginx plugin: the plugin edits whichever server block it
  # decides matches, and with a catch-all default server that is the wrong one.
  certbot certonly \
    --webroot -w "${WEBROOT}" \
    -d "${HOST}" \
    --cert-name "${HOST}" \
    --non-interactive --agree-tos --keep-until-expiring
fi

CONF="${SITES}/customer-${HOST}"
cat > "${CONF}" <<NGINX
# Generated by deploy/issue-cert.sh for a verified customer domain.
# Edits here are lost the next time that script runs for this host.
server {
    listen 80;
    listen [::]:80;
    server_name ${HOST};

    location /.well-known/acme-challenge/ {
        root ${WEBROOT};
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${HOST};

    ssl_certificate /etc/letsencrypt/live/${HOST}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${HOST}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    # Never public: it tells whoever asks which hostnames are verified.
    location /api/caddy/ {
        return 404;
    }

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
    }
}
NGINX

ln -sfn "${CONF}" "${ENABLED}/customer-${HOST}"

# Never reload a config that doesn't parse — that takes every site on the box
# down, not just this one.
if ! nginx -t; then
  rm -f "${ENABLED}/customer-${HOST}"
  echo "issue-cert: nginx rejected the config for ${HOST}; block disabled" >&2
  exit 4
fi

systemctl reload nginx
echo "issue-cert: ${HOST} is live over HTTPS"
